# Generated by Django 5.1.5 on 2025-02-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('status', models.CharField(choices=[('To Watch', 'To Watch'), ('Watched', 'Watched')], default='To Watch', max_length=20)),
            ],
        ),
    ]
